export PGHOST="localhost"
export PGPORT="5439"
export PGUSER="postgres"
export PGPASSWORD="postgres"
export PGDATABASE="osm"

export PGHOST="postgis"
export PGPORT="5432"
# PGUSER="postgres"
# PGPASSWORD="postgres"
# PGDATABASE="osm"
