FROM postgis/postgis:16-master

# Install GDAL and related tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gdal-bin \
        python3-gdal \
        osm2pgsql \
        wget \
        && rm -rf /var/lib/apt/lists/*

# Set a working directory for scripts
WORKDIR /scripts
